### ISSUE TITLE
👋 

### ISSUE THREAD

**Issue by benjamingr** [nodejs/open-standards#2]
I thought it would be useful to have a thread for the team where people involved with the team introduce themselves and their relation to open standards. @nodejs/open-standards 

We've done this in actual meetings before in other teams I've participated in and I figured trying to do it asynchronously could work/be nice instead. I've found knowing people and where they're coming from to be very useful in other teams.

I'll start myself, please add yourself in, if you'd rather not to that's also totally fine:

**Name:** Benjamin Gruenbaum

**Node Background:** I've been using Node since 0.6 and have been interested in core ever since. I got into Node core around promises related work initially and I've been a core collaborator since. I'm also a [modules team member](https://github.com/nodejs/modules) and a [moderator](https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#current-members-of-moderation-team). I also work with Node at Peer5 (my work).

**Standards Background:** I've participated in a few WHATWG meetings for various specs and made some small PRs to some standards (like fetch). I've provided feedback to several TC39 proposals in the past (async iterators, observables and to promises). I'm a little scared of bikeshed and the tooling don't have a lot of experience but am very interested in promoting standards. I also try to read all the mailing lists (like esdiscuss) and issues but I admit less so in the last 2-3 years since they got really noisy.

I also am a team member in some open source packages (MobX, Sinon, Bluebird, etc) 

**Other:** I'm from Tel Aviv (Israel), I am a dual Israeli/Polish citizen, I'm married (no kids yet) and have a nice dog. My hobbies are friends, working out, meditation and trekking.

**Comment by kenchris** [comment]
Oh sure,

**Name**: Kenneth Rohde Christiansen

**Background**: This will be a bit long, but I have been in this industry for a while :-)

Used to work at Nokia where I worked in a concepting team doing engaging modern UX (similar to today's UX but before iPhone). I then moved to work on WebKit by porting WebKit to EFL (Enlightenment Foundation Libraries) for a later cancelled Nokia project. Nokia acquired Qt and I moved to work on Qt WebKit instead, and Samsung took over the WebKit-EFL port for their Tizen project.

I got dedicated to improving mobile adaptations for WebKit like tiled backing store, pinch zoom, viewport meta tag, font boosting, hit region improvements for touch etc. Eventually new management coming from Mozilla background, decided that Nokia would abandon using Firefox for the Nokia N9 MeeGo device and out demo/testing browser turned into the official browser, so with a small 13 man team we delivered the first multi process WebKit based browser before Apple :-). Nokia eventually went all in on Windows and then failed, so I moved on to Intel as I could work from home, and many of my ex-team mates went to work at Apple on iOS Safari or WebKit.

At Intel, I initially got to work with Tizen and my old WebKit-EFL port :-) and then moved on to work mostly on Chromium and standards. I have now been here for approx 6 years or so and worked on multiple things related to web, internet-of-things, Node.js, standards and the like. 

I also got more into standards as Intel was part of the now defunct W3C SysApps working group together with Samsung, Mozilla and others. Many ideas that turned into PWAs later were discussed here.

On the hardware angle, I have been involved with Web Bluetooth and Web USB and am a co-editor for Web NFC, Generic Sensor APIs (multiple specs, like Orientation Sensors, Motion Sensor Explainer, Geolocation). I am also one of the people who helped make Progressive Web Apps a things and I am still heavily involved with that. For instance, I am a co-editor of the Web App Manifest spec.

Due to more work related to Intel Web strategy and more involvement in standardization, I ran for the W3C Technical Architecture Group (TAG) and became an elected member. From W3C point of view, we are chartered with the stewardship of the web platform.

Both due to this and because of my work at Intel, I am currently involved with a lot of different things, like JavaScript, Web Assembly, the Web Platform, etc. I really want to bring all these technologies, incl. Node.js and the Web Platform closer together, it just makes a lot of sense.

**Other**: I am Danish and work out of my home in the Copenhagen area. I often travel to different events and am a frequent speaker. I have also lived around 10 years outside my home country in such exotic places like Brazil and less exotic places like a few places Germany and the Netherlands :-). I am married and have a half Brazilian, half Danish little girl called Lea :-) which basically means that between travels and work, I have no spare time!

**Comment by rubys** [comment]
**Name**: Sam Ruby

**Node Background**: I've been an infrequent user of Node since its early days, most of my JavaScript usage has been on the web.  I started contributing to Node a few months ago, and became a contributor a few weeks ago.  I do have experience with a number of open source organizations, most notably [PHP](http://php.net/credits.php) and the [ASF](https://www.apache.org/foundation/).  A personal project of mine that might be of some interest: [ruby2js](https://github.com/rubys/ruby2js).

**Standards Background**: Joined TC39 with the intention of becoming the editor of ECMAScript in 1999, but was recruited to serve as the Conveener of the C# and .Net CLI WGs at ECMA 2000-2005.  I rejoined TC39 as a WG member from 2006-2009.  I was the secretary of the Atom Working Group from 2004-2007.  I was the HTML5 W3C WG co-chair from 2009-2015.  I was briefly an editor of the WHATWG URL specification, which I [discontinued](http://intertwingly.net/blog/2014/11/20/WHATWG-W3C-Collaboration) when I found that browsers vendors generally were uninterested in [complying with that spec](http://intertwingly.net/stories/2014/10/16/urltest-results/).

**Author**: [Agile Web Development With Rails](https://pragprog.com/book/rails5/agile-web-development-with-rails-5) and [RESTful Web Services](http://shop.oreilly.com/product/9780596529260.do).

**Other**: I live in Raleigh, NC (USA).  I work for IBM (37 years).  I've been married for 36 years, two kids, both grown.

**Comment by devsnek** [comment]
**Name:** Gus

**Node Background:** I've used Node.js since right after the merge and I've been involved as a collaborator since November. Currently my primary work with Node.js is implementing ESM for general use and `vm`.

**Standards Background:** I've participated lightly in W3C and TC39. I'm working a little bit with WHATWG at the moment. I'm very interested in spec reality and implementation. ecmarkup > bikeshed.

**Other:** I'm an student in Chicago. Working towards majoring in CS. My open source work consists almost exclusively of JavaScript-related things.

**Comment by joyeecheung** [comment]
**Name**: Joyee Cheung (Qiuyi Zhang in Mandarin, most people just call me Joyee)

**Node Background**: I started to use Node.js around 2014, got my first job at Alibaba as a Node.js developer in 2016, became a collaborator since January 2017, and joined CTC (later merged into TSC) in May 2017. I mostly worked on diagnostics and maintained an internal fork of Node.js at my previous job. I work on various subsystems in Node.js core and on a few other projects under the Node.js organization. 

**Standards Background**: I was involved in the implementation of WHATWG URL in Node.js, and I am working on automating WPT updates in Node.js core. I joined the compilers team at Igalia a few months ago and worked on a few language features/fixes in V8/test262.

**Other**: I grew up in Guangzhou and now live in Hangzhou, China. I travel a few times a year to attend/speak at conferences/meetings and to visit the headquarter of my company (Igalia) in Spain.

**Comment by mcollina** [comment]
**Name**: Matteo Collina

**Node Background**: I've been using Node since 0.2 and have been interested in core ever since. I got into Node core around streams. I'm the maintainer of [readable-stream](readable-stream) (the most downloaded module of npm). I've been a TSC member for about a year. I'm a Principal Architect at nearForm - when not working on Node.js I'm in the trenches helping companies adopt and use Node.js. I'm also the curator of NodeConf.eu, and in the selection committee of several EU conferences. 

**Standards Background**: None. 

**Other**: I'm live in Forlì (Italy), I'm married (no kids yet) and have a tiny poodle. I've a Ph.D..

**Comment by ljharb** [comment]
**Name**: Jordan Harband

**Node Background**: I've been maintaining [nvm](http://nvm.sh) since 2014 or so, and added io.js support so that users could test with it on travis-ci soon after its release which meant working with the build team directly. I've been in `#node.js` on freenode (as a user, and then as an op) for a bit longer than that, and am an admin on the [node.js slack](https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#admins-for-nodejs-slack-community). I've participated in many discussions around implementations in node, and am currently a member of the [Version Management working group](https://github.com/nodejs/version-management/) and the [Modules working group](https://github.com/nodejs/modules).

**Standards Background**: I started out maintaining and then taking over [es5-shim](https://github.com/es-shims/es5-shim) and [es6-shim](https://www.github.com/paulmillr/es6-shim). I've been a TC39 member since the end of 2014, initially for Twitter and now for @Airbnb. I'm also one of the three editors for the spec itself post-ES2018. I've worked extensively with many language proposals, as well as discussing some of their babel implementations, and publish many [spec-compliant shims](https://www.npmjs.com/search?q=keywords:%22es-shim%20API%22) on npm.

**Other**: I grew up and live in the SF Bay Area; I'm married, and have an 18 month old daughter and a [3 year old mini labradoodle](https://www.instagram.com/mochidoodledog/).

**Comment by TimothyGu** [comment]
**Name:** Tiancheng "Timothy" Gu (Simplified Chinese: 顾天骋)

**Node.js Background:** I [stumbled upon](https://timothygu.me/2015/01/24/node-js/) Node.js back in 2014–2015 and quickly fell in love with the language, the runtime, and the community. Before joining Core development I was a maintainer for Jade/[Pug](https://pugjs.org/) for some time and [EJS](http://ejs.co/) for a shorter time. I got into Core development as part of the effort to create the [WHATWG URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api), and since becoming a Collaborator I've been active in the development of [`inspector`](https://nodejs.org/api/inspector.html) and [`vm`](https://nodejs.org/api/vm.html) modules. I'm also responsible for (co-)maintaining several Node.js modules, like [node-fetch](https://github.com/bitinn/node-fetch) and [jsdom](https://github.com/jsdom/jsdom). I'm currently on the [TSC](https://github.com/nodejs/TSC) with Joyee and Matteo.

**Standards Background:** I became active in the [WHATWG](https://whatwg.org/) when I was working on the URL parser, and never really stopped. I've been active in editing several specs like [HTML](https://html.spec.whatwg.org/multipage/) and [Web IDL](https://heycam.github.io/webidl/), and this summer I've been working on a new specification for [`document.open()`](https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-document-open) for @google. I've also worked with TC39 on a few occasions, writing a [guide on how to read the ECMAScript spec](https://timothygu.me/es-howto/) as well as attending the last TC39 meeting in July 2018.

**Other:** I'm entering my second year of university at @UCLA, majoring in Computer Science. While I'm located in New York City for the summer, I will be returning to Los Angeles pretty soon. I grew up in Shanghai, China, and speak a bit of the [local tongue](https://en.wikipedia.org/wiki/Shanghainese), but have been living in the vicinity of Los Angeles, USA for the past ~7 years.

**Comment by apapirovski** [comment]
**Name:** Anatoli Papirovski

**Node.js Background:** I've been sort of using Node.js since early 2010s but I only started seriously working with it in 2015. I started contributing to Core in mid 2017 as I was trying to use the `http2` module but found the compatibility mode wasn't truly "compatible". My main contributions have been to http2, timers, test reliability, as well as a bunch of performance changes throughout Core.

**Standards Background:** I haven't really been involved in any Standards work, although I have closely followed ECMAScript specs for years. I used to contribute to WebKit a great many years ago, focusing on spec compliance.

**Other:** I'm married and have a 9 year old Weimaraner named Cache. We've recently moved from Toronto to San Francisco so adjusting to that has been taking up a significant amount of my time. I was born in St. Petersburg, Russia and grew up in the Czech Republic.

**Comment by jasnell** [comment]
Name: James Snell

Node.js background: Became involved with Node.js project in Jan 2015 as IBM's technical lead for Node.js. Helped in the process of bringing io.js and Node.js back together, helped getting the Foundation going. Wrote a bunch of code.

Standards background: 17 years of standards work in some way or another. WS-* (sorry), Atom, Activity Streams, few ietf internet drafts, w3c stuff, etc.

Other: married, 4 kids, 3 dogs, new house, way too many boxes to unpack.

**Comment by MylesBorins** [comment]
**Name**: Myles Borins

**Node.js background**:

Started using node (0.6) in 2012 as part of an art installation to get a browser and Max / MSP to communicate to one another. Instantly fell in love and it became one of the most relied on tools in my tool box for getting things done with computers. The first platform I really used node on was the raspberry pi!

Entered the workforce in 2014 writing JavaScript tooling using Node.js. That job led to an opportunity with IBM to work on Node.js core full time in 2015. Currently working at Google as a DA on Cloud Platform where a good chunk of my time is still spent helping to maintain core.

**Standards background**:

I've been attending TC39 for about 1.5 years now. My first proposal, [Top-Level Await](https://github.com/tc39/proposal-top-level-await), is currently stage 2. I've dropped a message or two into the WhatWG repos. I've also recently joined the W3C web audio working group

**Other**

I love pinball!

**Comment by bnb** [comment]
**Name:** Tierney Cyren

**Node.js Background:** First tried Node.js in ~0.8 but the lack of documentation and quality/up-to-date educational material pushed me away. Tried again around ~0.10.13 and found the same problems. I joined the io.js community contributing to the Website WG and spinning the Evangelism WG out of it while in college. Because of new life circumstances, I started looking for a job focusing on Node.js with a semester of college left – at that point, I got an internship at NodeSource that I eventually turned into a role as a Developer Advocate with a substantial amount of time that I could dedicate to community-focused work in the Node.js project. I've been a part of the Node.js Community Committee for ~1.5 years and have served as its chair for 1 year.

Standards Background: None, due to lack of an obvious path. Web Standards have always been an area of extreme interest to me – specifically the standards bodies around HTML and web standards that focus on protocols.

**Other:** I'm currently in the process of moving to Brooklyn (yay!) with my wife, spend a non-trivial amount of time on video games (you'd be surprised how many involve Node.js + web standards somewhere in their deployments), and 💚 developer tooling.

**Comment by littledan** [comment]
**Name**: Daniel Ehrenberg

**Node Background**: I'm not really a Node user or developer beyond simple command-line workflows, but I've worked on V8 and TC39 trying to take Node's needs into account, and made a PR against the web Buffer package for ES6 compatibility.

**Standards Background**: I've been a TC39 delegate for 3 years, having worked on BigInt, class features, RegExp features, web compat fixes for ES6, etc. As vice-chair of the committee, my priority is inclusion, which for me in this context includes making sure that core ecosystem stakeholders like Node are well-represented in TC39. Also visited CSSWG once, have a couple PRs landed in WebIDL, edited the WebAssembly JS API/Web API specs, have some PRs out for review in HTML, am the editor of ECMA-402 (Intl).

**Other**: I'm from Rochester, NY, lived in Minnesota and San Francisco before ending up in a town outside of Barcelona with my husband.
